version: "3"
services:
  flaskapi:
    container_name: flaskapi
    # image: flaskapi
    build: .
    volumes:
      - appdb:/etc/todos
    ports:
      - 3000:5000
    networks:
      - app

    environment:
      - REDIS_PORT=3000

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - app

# Cette section crée un disk de storage pour l'environment muti-conteneur à déployer
volumes:
  appdb:
    driver: local

# Cette section crée un réseau virtuel pour l'environment muti-conteneur à déployer
networks:
  app:
    # driver: bridge
  # frontend:
  #   # driver: bridge